### ISSUE TITLE
과제 02 이슈

### ISSUE THREAD

**Issue by EthanSeok** [xxxjjhhh/ppp2024#1]
## 과제 02 이슈 내용
* 계산 실수 및 변수 사용 여부

## 코멘트
```python
# 키와 몸무게가 임의로 주어졌을 때 BMI를 구하시오
# BMI = 몸무게 (kg) / 키 (m)^2
# weight = 60, height = 170

weight = 60
height = 170

mHeight = 170/100

bmi = weight / mHeight*mHeight
print(bmi)
```

* `bmi = weight / mHeight*mHeight`를 `bmi = weight / (mHeight*mHeight)`로 수정하여야 합니다. 나눗셈이 먼저 계산되어 결과가 다릅니다. 수식 작성시 `()` 사용에 유의하여야 합니다.

```python
# 밑변이 5, 윗변이 3, 높이가 4인 사다리꼴의 면적을 구하시오.

top = 3
bottom = 5
height = 4

area = (3 + 5) * 4 / 2
print(area)
```

* `top`, `bottom` , `height` 3가지 변수를 활용하여 계산하는 것을 권장합니다. 변수를 할당하지 않으면, 숫자 수정시 변수 한번 수식 한번 각각 두 번 수정해야하는 번거러움이 발생합니다. 프로그래밍의 목적은 번거러움을 줄이기 위함입니다. 수고하셨습니다.

**Comment by xxxjjhhh** [comment]
수정 완료 하였습니다.
