### ISSUE TITLE
과제11

### ISSUE THREAD

**Issue by taegon** [xxxjjhhh/ppp2024#3]
과제를 잘 수행하고 있네요.
과제11에서 5개의 문제에서 공통된 함수가 재이용되고 있기 때문에, import 문을 이용해 보세요.
과제 4, 5에서 sumifs는 같은 코드인데, 다른 인자를 쓰고 있습니다. 다소 오해할 수 있습니다.
물론 과제로는 훌륭합니다. sumifs와 같이 일반적인 용도로 쓸 때는 month, year라는 특수한 변수명 보다는 포괄적으로 쓸 수 있는 단어를 쓰기 바랍니다. 참고로 엑셀에서는, sum_range, criteria_range1, criteria1, criteria_range2, criteria2, ... 이런식으로 변수명이 이루어집니다.

**Comment by xxxjjhhh** [comment]
교수님 피드백 감사드립니다! 리팩터링 진행하겠습니다.
