### ISSUE TITLE
과제12 리뷰

### ISSUE THREAD

**Issue by taegon** [xxxjjhhh/ppp2024#4]
과제를 아주 잘 하고 있습니다.
잘 하고 있기 때문에, 더 나은 코드를 만들면서 몇 가지 고민을 해봤으면 합니다.

메인함수에서 호출할 때, 인자가 너무 많습니다. 아래 코드에서 특히 41번째 줄을 보면 함수 호출 할 때 코드가 너무 깁니다. 나중에 keyword arguments (named arguments)를 배우면, 좀 낫긴 할텐데, 인자가 5개가 되면 순서가 헷갈릴 수 있습니다. 수업시간에는 인자를 줄이기 위해서 year, month, day를 각각 쓰지 않고 하나로 묶어서 dates로 사용했었습니다.
https://github.com/xxxjjhhh/ppp2024/blob/edd21fd7c9468df5c282e2f2690cb64f01b02946/hw12/sol03_gdd_200_over.py#L37-L41

그리고 아래 코드 역시 고민해 볼 수 있는 부분이 이렇게 코드를 짜면 전체 데이터를 다 훑어야 합니다.
만약 데이터가 연도별로 쪼개져 있고, gdd가 200이 넘는 순간에 더 이상 계산할 필요가 없으므로, 28번째 줄 다음에 break나 return으로 반복문을 종료하고 gdd 200이상을 만족한 시점부터 그 이후 데이터를 계산하지 않을 수 있습니다. 이 경우(gdd 200)에는 4월 말즈음에 조건을 만족할 것이므로, 매년 4달 정도 자료(120개)만 계산하면 됩니다. 하지만 지금 코드 구조로는 전체 다 돌려야 하므로, 365개를 돌려야 하니, 계산량이 3배쯤 많게 됩니다. 지금 코드에서는 사전형에서 키의 존재 유무를 찾고, 데이터가 많지 않기 때문에, 계산 시간이 큰 문제는 아닙니다만, 대량의 자료를 처리하거나, 웹으로 대량의 접속자에 대응한다고 하면, 이런 간단한 작업에도 이슈가 있습니다.
또한 다른 언어를 배워서 조건문에서 short circuit를 알텐데, 26번째 줄 조건 2개는 앞뒤를 바꾸면 좀 더 효율적일 것 같네요. 현재 문제에 한해서요.
https://github.com/xxxjjhhh/ppp2024/blob/edd21fd7c9468df5c282e2f2690cb64f01b02946/hw12/sol03_gdd_200_over.py#L14-L30

**Comment by taegon** [comment]
@ethanseok TA도 이 논의는 참고하기 바랍니다.

**Comment by xxxjjhhh** [comment]
감사합니다. 교수님 :) 리팩터링 진행하겠습니다.

**Comment by xxxjjhhh** [comment]
@taegon 
최근에 본 영상에도 교수님께서 말씀하신 내용이랑 비슷한 영상이 있어 링크 참조합니다!
https://youtu.be/5dm7GVsZJLw?si=KRWlBSHJ92YFBXjX
